// The real talks of Devoxx Belgium 2026, from the public schedule (dvbe26.cfp.dev/api/public/schedules), fetched on 2026-10-04.
// Titles only: no speaker names. Every session now has its room on the schedule, and the game uses it.
// Per day (Monday..Friday): [room, from, to, type, title]; room is a Devoxx room number (3–10) or 'bof1' / 'bof2' downstairs.
// Refresh with: node tools/talks.mjs
export const TALKS = [
  [
    [4,"09:30","12:30","Deep Dive","Solving Multimodal and Long-Context Challenges"],
    [5,"09:30","12:30","Deep Dive","Agent Loops, Decoded: Fundamentals to Agentic Patterns in Spring AI"],
    [6,"09:30","12:30","Deep Dive","From AI to Agent: A Field Guide to Agentic Patterns in LangChain4j"],
    [8,"09:30","12:30","Deep Dive","From Autocomplete to Autopilot: How AI Is Changing the Developer Experience"],
    [9,"09:30","12:30","Deep Dive","Prompt It Right: Spring Boot Testing in the AI Era"],
    ["bof2","09:30","12:30","Hands-on Lab","🚀 From Java to AI: Build Your First Intelligent Agent System!"],
    ["bof1","10:30","12:30","Hands-on Lab","Java is for Data Science, Too: Building an End-to-End ML Pipeline Without Leaving the JVM"],
    [4,"12:40","13:20","Lunch Talk","Introduction to Spring AI"],
    [5,"12:40","13:20","Lunch Talk","Destructoring is the future of Javas Encapsulation"],
    [6,"12:40","13:20","Lunch Talk","Java, LEGO & AI: Teaching the Next Generation to Build, Not Just Prompt"],
    [4,"13:30","16:30","Deep Dive","Can AI Build a Jakarta EE Runtime? The Vidocq Experiment"],
    [5,"13:30","16:30","Deep Dive","Modern Java in Practice - The Features That Matter"],
    [6,"13:30","16:30","Deep Dive","Codepocalypse Now: LangChain4j vs JetBrains Koog"],
    [8,"13:30","16:30","Deep Dive","From Developer to Builder: A Spec-Driven Development Deep Dive"],
    [9,"13:30","16:30","Deep Dive","The Quarkus advantage: Turning build-time metaprogramming into runtime performances"],
    ["bof1","13:30","16:30","Hands-on Lab","Using Structured Concurrency and Scoped Values to Create a Virtual Threads Based Asynchronous Application"],
    ["bof2","13:30","16:30","Hands-on Lab","Building Autonomous AI Agents with Spring"],
    [4,"16:50","17:20","Tools-in-Action","Expanding Vector Search Beyond Similarity"],
    [5,"16:50","17:20","Tools-in-Action","Your AI Agent Trusts Strangers. Let Me Show You."],
    [6,"16:50","17:20","Tools-in-Action","The day we stopped publishing Kafka event from our API..."],
    [8,"16:50","17:20","Tools-in-Action","Secure Your Coding Agent Like It’s Malware"],
    ["bof1","16:50","18:50","Hands-on Lab","Wiring Up the AI Mesh: Building A2A-Compliant Java Agents"],
    ["bof2","16:50","18:50","Hands-on Lab","From Install to Insight: A Hands-On GPU Lab for Java Developers"],
    [4,"17:35","18:05","Tools-in-Action","Beyond Code: The Intent-Driven IDE for the Agentic Age"],
    [5,"17:35","18:05","Tools-in-Action","Teaching a New Dog Old Tricks: Give the Agent a Debugger"],
    [6,"17:35","18:05","Tools-in-Action","In the loop, not in the dark: staying in control in the era of dark software factories"],
    [8,"17:35","18:05","Tools-in-Action","Stopping AI-Generated Architectural Drift: Deterministic Guardrails for Agentic Coding"],
    [4,"18:20","18:50","Tools-in-Action","Building the Trusted Agent Ecosystem"],
    [5,"18:20","18:50","Tools-in-Action","One tool to rule them all: bash, a tiny LLM, and the birth of a coding agent"],
    [8,"18:20","18:50","Tools-in-Action","Testing Architecture Made Simple"],
    ["bof1","19:00","20:00","BOF","Hi, Belgian Java Community, we want to meet you!"],
    ["bof2","19:00","20:00","BOF","LangChain4j Community BOF"],
  ],
  [
    [4,"09:30","12:30","Deep Dive","Cheaper or Better? The Strategic Choice Behind AI Adoption"],
    [5,"09:30","12:30","Deep Dive","Learning modern Java the playful way"],
    [6,"09:30","12:30","Deep Dive","Building AI Agents from First Principles"],
    [8,"09:30","12:30","Deep Dive","Loop Engineering, beyond prompt, context, and harness engineering"],
    [9,"09:30","12:30","Deep Dive","Will Valhalla Fix Tony's Billion-Dollar Mistake?"],
    ["bof1","09:30","12:30","Hands-on Lab","👩‍💻 Developing with AI: What if it were as simple as adding a library? 🧑‍💻"],
    ["bof2","09:30","12:30","Hands-on Lab","From code to control: master deployments with Feature Flagging and OpenFeature"],
    [4,"12:40","13:20","Lunch Talk","From Developer to Story Builder: Engineering a Novel, an ARG, and a Transmedia World with AI"],
    [5,"12:40","13:20","Lunch Talk","Beyond system.out.println: Applying a Debugging Mindset at Scale"],
    [8,"12:40","13:20","Lunch Talk","Measuring the Unmeasurable: Evaluating Generative AI in Practice"],
    [4,"13:30","16:30","Deep Dive","Don’t burn your fingers in the heat of the AI (r)evolution. (And get an OpenClaw)."],
    [5,"13:30","16:30","Deep Dive","AI Security Deep Dive, Securing Agents and AI Applications"],
    [6,"13:30","16:30","Deep Dive","Specialized AI Agents: from concept to production"],
    [8,"13:30","16:30","Deep Dive","Responsibly Dimming the Lights in the Software Factory"],
    [9,"13:30","16:30","Deep Dive","Write Java Code Like a Seasoned Hacker: 2026 Edition"],
    ["bof1","13:30","16:30","Hands-on Lab","Technical Workshop on AI-Native Tooling for Java Development"],
    ["bof2","13:30","16:30","Hands-on Lab","Beyond the Chatbox: Ship On-Device AI in Your Browser"],
    [4,"16:50","17:20","Tools-in-Action","Tap into the NVIDIA Ecosystem from Java with TornadoVM's Hybrid API"],
    [5,"16:50","17:20","Tools-in-Action","Solving Distributed Transactions with the Saga Pattern and Temporal"],
    [6,"16:50","17:20","Tools-in-Action","30 minutes to build your first Vidocq app, the 100% European Sovereign Java stack with zero external dependencies"],
    [8,"16:50","17:20","Tools-in-Action","🧰 Dev Containers: the ultimate toolbox for developers?"],
    [9,"16:50","17:20","Tools-in-Action","BootUI, the missing developer console for Spring Boot and Quarkus"],
    ["bof1","16:50","18:50","Hands-on Lab","Analyze and Optimize Your Applications with JFR"],
    ["bof2","16:50","18:50","Hands-on Lab","Building Production-Ready Agentic Systems with LangChain4j and Quarkus"],
    [4,"17:35","18:05","Tools-in-Action","From Laptop to Lakehouse: Analytical SQL with DuckDB"],
    [5,"17:35","18:05","Tools-in-Action","The Magic of OpenTelemetry: Rewriting Your App in Production"],
    [6,"17:35","18:05","Tools-in-Action","Beyond assertEquals: Probabilistic Security and Bias Testing for Java LLM Applications"],
    [8,"17:35","18:05","Tools-in-Action","AsyncAPI in action: OpenAPI for event-driven applications"],
    [9,"17:35","18:50","Documentary","The Java Story | The Official Documentary"],
    [4,"18:20","18:50","Tools-in-Action","Do We Need a Build Language? Java Builds Java"],
    [5,"18:20","18:50","Tools-in-Action","Java Script (No, Not That One): Modern Automation with Java"],
    [6,"18:20","18:50","Tools-in-Action","Exquisite Evals for Skills & MCPs"],
    [8,"18:20","18:50","Tools-in-Action","The Importance of HITL to Avoid Chaos and EU Regulations for AI"],
    ["bof1","19:00","20:00","BOF","Quarkus Community BOF"],
    ["bof2","19:00","20:00","BOF","Who will build software after AI?"],
  ],
  [
    [8,"09:30","09:50","Keynote","Welcome to Devoxx"],
    [8,"09:50","10:10","Keynote","From Brainless to Brilliant — Giving an Open-Source Robot a Mind of Its Own"],
    [8,"10:10","10:30","Keynote","Half of a billion Idle GPUs: The Case for On-Device AI"],
    [8,"10:30","10:50","Keynote","A Fleet of AI Agents, Each in Its Own Sandbox: Inside Docker's Agentic Platform"],
    [8,"10:50","11:10","Keynote","The Year of the Runtime"],
    [8,"11:10","11:30","Keynote","Agentic Engineering Reconversion"],
    [3,"12:00","12:50","Conference","Build the Builder: A Java Coding Agent in Your IDE with ACP"],
    [4,"12:00","12:50","Conference","Emergent DevEx: The Good, the Bad, and the Legacy"],
    [5,"12:00","12:50","Conference","Structured Concurrency Looms"],
    [6,"12:00","12:50","Conference","I Hired a Real Robot as My Junior Dev — and Now My Kids Don't Want to Learn Java Anymore"],
    [7,"12:00","12:50","Conference","Post-Quantum Today: How Your Passwords Will Be Safe in a Quantum Future"],
    [8,"12:00","12:50","Conference","Fun with Flags: How OpenFeature Solves Your Feature Flag Headaches"],
    [9,"12:00","12:50","Conference","MCP 2.0 - Stateless, New Auth (CIMD), and Exciting Extensions"],
    [10,"12:00","12:50","Conference","Wrap, Reshape, or Redesign: Retrofitting Your APIs for a World of Agents"],
    [3,"13:05","13:45","Lunch Talk","Mission Possible: The 45-Minute Path to Bullet-Proof Java Container Images"],
    [4,"13:05","13:45","Lunch Talk","Eval Driven Development: Why you need it to make your Agentic Application survive Production"],
    [5,"13:05","13:45","Lunch Talk","From User Prompt to JPA Query: Comparing Tool Calling, Structured Output & Hybrid Approach"],
    [6,"13:05","13:45","Lunch Talk","Engineering for the Long Haul: Operating Open Source at Scale"],
    [7,"13:05","13:45","Lunch Talk","Safety, speed, and governance in the agentic era"],
    [8,"13:05","13:45","Lunch Talk","Life in the Ivory Tower: Confessions of a Former Developer Who Turned Into an Architect"],
    [9,"13:05","13:45","Lunch Talk","What rules the virtual? How our systems obey physical laws."],
    [10,"13:05","13:45","Lunch Talk","Let's dance! – Teaching your robot some moves with reinforcement learning"],
    [3,"14:00","14:50","Conference","Run Frontier Open Models on consumer hardware"],
    [4,"14:00","14:50","Conference","Deterministic by Design - Achieving Reproducible Builds with Maven"],
    [5,"14:00","14:50","Conference","Harness Engineering: Building the System Around Your AI Coding Agent"],
    [6,"14:00","14:50","Conference","The pizza party of the future 🍕 software teams and product value in the age of coding agents"],
    [7,"14:00","14:50","Conference","G1, ZGC, Shenandoah, ... with all these GCs in Java, which one do I choose?"],
    [8,"14:00","14:50","Conference","A Year of Agentic AI Evolution: Lessons Learned Building Production-grade Agentic Systems"],
    [9,"14:00","14:50","Conference","Java, Raspberry Pi, and the Art of Overengineering Everyday Life"],
    [3,"15:10","16:00","Conference","Integration patterns for distributed systems"],
    [4,"15:10","16:00","Conference","Teaching an Old Handle New Tricks: From Core Reflection to FFM"],
    [5,"15:10","16:00","Conference","How to survive and thrive as a dev (team) in the exponential age of AI. Real-world AI adoption, smarter ways of working, and lessons from the front lines"],
    [6,"15:10","16:00","Conference","Why Documentation Won’t Write Itself—and AI Won’t Save You"],
    [7,"15:10","16:00","Conference","CRAcking Compliance - The EU Cyber Resilience Act"],
    [8,"15:10","16:00","Conference","Bootiful Spring Boot 4"],
    [9,"15:10","16:00","Conference","0 to 350 Engineers on Claude Code: What Could Go Wrong?"],
    [10,"15:10","16:00","Conference","Pragmatic multi-cloud architecture: designing for resilience and portability beyond the hype"],
    [3,"16:40","17:30","Conference","Surviving the \"AI Slopageddon\": How AI shakes the foundations of Open Source"],
    [4,"16:40","17:30","Conference","GraalVM Next: Layers, Crema, and WebAssembly in Action"],
    [5,"16:40","17:30","Conference","Consistency Patterns in Event-Driven Architecture"],
    [6,"16:40","17:30","Conference","Big Runtimes Make Efficient Programs"],
    [7,"16:40","17:30","Conference","Building an Agent Ready Platform"],
    [8,"16:40","17:30","Conference","Architecture Observability and Guardrails"],
    [9,"16:40","17:30","Conference","AI Made Building Cheap. Now Decisions Are the Bottleneck."],
    [10,"16:40","17:30","Conference","Building LLM Inference Engines in Java with TornadoVM and the NVIDIA Ecosystem"],
    [3,"17:50","18:40","Conference","A Deserter Returns: What the Java community helped me rediscover"],
    [4,"17:50","18:40","Conference","No Country For Old APIs. Wrapping legacy Java services as MCP tools without rewriting them."],
    [5,"17:50","18:40","Conference","rm -rf self-doubt: Debugging Impostor Syndrome for Developers"],
    [6,"17:50","18:40","Conference","When benchmarks go bad - what we learned from measuring performance wrong"],
    [7,"17:50","18:40","Conference","Beyond encryption at rest: computing on encrypted data"],
    [8,"17:50","18:40","Conference","Kubernetes for Developers"],
    [9,"17:50","18:40","Conference","Create your own AI Agents without code"],
    [10,"17:50","18:40","Conference","Quarkus Meets Leyden at the JVM Performance Edge"],
    ["bof1","18:50","19:50","BOF","GraalVM Community BOF"],
    ["bof2","18:50","19:50","BOF","Getting started with speaking: Your first conference talk"],
  ],
  [
    [3,"09:30","10:20","Conference","Rewriting the rules: How AI transforms engineering and inspiring young minds"],
    [4,"09:30","10:20","Conference","Java on Kubernetes Without Container Images: The WebAssembly Way"],
    [5,"09:30","10:20","Conference","From vibe coding to harness engineering: modernizing a regulated environment with AI"],
    [6,"09:30","10:20","Conference","Toxic Flows in MCP Servers and Skills: What Your Agent Blindly Trusts"],
    [7,"09:30","10:20","Conference","Snake in 10 Lines: Learning More by Coding Less"],
    [8,"09:30","10:20","Conference","223 Pull Requests in 11 Days: The Recipe for Building Real Software with AI Agents"],
    [9,"09:30","10:20","Conference","Software Monuments - Architectural Lessons from the Systems That Shaped Computing"],
    [10,"09:30","10:20","Conference","Project Detroit: From Foreign Libraries to Foreign Language Runtimes"],
    [3,"10:40","11:30","Conference","Hey Belfius! Meet our new bank AI assistant—and discover how we’re building and securing AI across Belfius."],
    [4,"10:40","11:30","Conference","Reflect, Transform, Accelerate: Bringing GPU Computing to Java"],
    [5,"10:40","11:30","Conference","Coder, Coach, Catalyst - using questions to make people grow"],
    [6,"10:40","11:30","Conference","How to Architect Green Software"],
    [7,"10:40","11:30","Conference","High-Performance Java-Native AI with CUDA and the Vector API"],
    [8,"10:40","11:30","Conference","Agents With Seatbelts: Practical Ways to Keep AI Code Gen Under Control"],
    [9,"10:40","11:30","Conference","When ORM Becomes OMG: Performance Pitfalls in JPA and Friends"],
    [10,"10:40","11:30","Conference","Dream Machines & Walled Gardens"],
    [3,"11:50","12:40","Conference","State of Agentic Coding"],
    [4,"11:50","12:40","Conference","Quixotic: Pure Java Inference at Native Speed"],
    [5,"11:50","12:40","Conference","The Yearly Java Performance Update for 2026"],
    [6,"11:50","12:40","Conference","The Rise of Agent Enablement: Coding Agents Don't Scale Themselves. Neither Do Your Teams."],
    [7,"11:50","12:40","Conference","Say Goodbye to LLM API keys with Workload Identity Federation"],
    [8,"11:50","12:40","Conference","Taming Microservice Overload: Our Journey to Modular Monoliths"],
    [9,"11:50","12:40","Conference","Making sense of vector databases"],
    [10,"11:50","12:40","Conference","SIMD for Java: how Elasticsearch already benefits from the Panama Vector API"],
    [3,"12:55","13:35","Lunch Talk","Engineering Lessons from Working on Software Older Than Me"],
    [4,"12:55","13:35","Lunch Talk","\"You May Now Optimize the Wedding\": Optimizing the Seating, Bachelor Party, and Honeymoon with Constraint AI"],
    [5,"12:55","13:35","Lunch Talk","Agents Shouldn't Control Control Flow"],
    [6,"12:55","13:35","Lunch Talk","Green Maven builds: sustainable CI in practice"],
    [7,"12:55","13:35","Lunch Talk","Keeping Spring Applications Secure in the Age of AI"],
    [8,"12:55","13:35","Lunch Talk","Is the IDE dead ?"],
    [9,"12:55","13:35","Lunch Talk","Who to blame? The AI, The Programmer, or The Prompt?"],
    [10,"12:55","13:35","Lunch Talk","The Devoxx Robot Games"],
    [3,"13:50","14:40","Conference","Building, Shipping and Governing AI Agents on Kubernetes"],
    [4,"13:50","14:40","Conference","Taming the Chaos: Security and Predictability in LLM-Powered Applications"],
    [5,"13:50","14:40","Conference","Software engineering in the age of AI agents: who’s in control?"],
    [6,"13:50","14:40","Conference","Conquest, time travel and explosions using Git"],
    [7,"13:50","14:40","Conference","Ask the Architects"],
    [8,"13:50","14:40","Conference","The Hexagonal Hangover"],
    [9,"13:50","14:40","Conference","Java and the Next Generation of Programming Models"],
    [10,"13:50","14:40","Conference","Hardwood: Building a Parquet Parser From Scratch (With a Little Help From AI)"],
    [3,"15:00","15:50","Conference","Modernizing legacy code with AI: hands-on examples & lessons learned"],
    [4,"15:00","15:50","Conference","Beyond the Pod: Architecting and Scaling AI Agents on Kubernetes"],
    [5,"15:00","15:50","Conference","Kill All Mutants! (Intro to Mutation Testing)"],
    [6,"15:00","15:50","Conference","Build a private cluster for the office"],
    [7,"15:00","15:50","Conference","Faster Development with Java, Python, and Micronaut"],
    [8,"15:00","15:50","Conference","The Dark Secrets of Computer Science"],
    [9,"15:00","15:50","Conference","Why Java Is Perfect for AI - Just Not the AI You’re Thinking Of"],
    [10,"15:00","15:50","Conference","Underneath the Black Marker: AI Techniques for Detecting and Reversing Redactions"],
    [3,"16:30","17:20","Conference","Owning the inference layer: When and how to run your own models"],
    [4,"16:30","17:20","Conference","Knocking on the Wrong Door: The Six Developers You’ll Meet in Security"],
    [5,"16:30","17:20","Conference","Owning the Code You Didn't Type"],
    [6,"16:30","17:20","Conference","Everyday JSON"],
    [7,"16:30","17:20","Conference","Choose your own adventure in agentic design patterns"],
    [8,"16:30","17:20","Conference","ADRs: The Why and How"],
    [9,"16:30","17:20","Conference","Microservices Without the Distributed Mess"],
    [10,"16:30","17:20","Conference","How I built my own intelligent Robot Arm from Scratch"],
    [3,"17:40","18:30","Conference","Production-Ready Java Containers: Smaller, Faster, Smarter"],
    [4,"17:40","18:30","Conference","From a startup stack to 5 microseconds: inside a crypto trading engine"],
    [5,"17:40","18:30","Conference","Help! I hate my team mate!"],
    [6,"17:40","18:30","Conference","AI in the Dark: Running LLMs in Air-Gapped Production Environments"],
    [7,"17:40","18:30","Conference","Decoding the Cosmos: Voyager's 1970s Algorithms Meet Today's Cutting-Edge Tech"],
    [8,"17:40","18:30","Conference","Bootiful Security"],
    [9,"17:40","18:30","Conference","Their API Went Down. So Why Is My App on Fire?"],
    [10,"17:40","18:30","Conference","Introducing Agent Control Theory: The System Runs the Model"],
    ["bof1","18:50","19:50","BOF","What Does it Print? The Java Quiz (Hard Edition 🤯)"],
    ["bof2","18:50","19:50","BOF","Open Source in the Age of AI: Where's the value?"],
    [5,"18:55","19:40","Closing Keynote","F*ck The System, and other bad ideas for the future"],
  ],
  [
    [4,"09:30","10:20","Conference","The Praxis proxy or: How I Learned to Stop Worrying and Love AI workloads"],
    [5,"09:30","10:20","Conference","Escaping Java's Allocation Gravity with Value Classes"],
    [6,"09:30","10:20","Conference","Why it takes 3000 commits to bring Valhalla's value objects to the JDK"],
    [8,"09:30","10:20","Conference","All you need to know about Maven 4!"],
    [9,"09:30","10:20","Conference","The Quantum Tech Lead: Hands-On and Abstract at the Same Time"],
    [4,"10:40","11:30","Conference","Embabel Agent v1.5"],
    [5,"10:40","11:30","Conference","Is AI killing XP practices? (Or are we letting it?)"],
    [6,"10:40","11:30","Conference","What’s happening with Project Amber?"],
    [8,"10:40","11:30","Conference","You thought technical debt was bad? Meet design debt!"],
    [9,"10:40","11:30","Conference","10 Billion Records vs. The Regulator: An Architectural Post-Mortem of an 11TB Exadata Failure"],
    [4,"11:50","12:40","Conference","My old trains have a second life, with TinyGo!"],
    [5,"11:50","12:40","Conference","10 boring reasons why Java is the best ecosystem for agentic development"],
    [6,"11:50","12:40","Conference","Java Next - From Valhalla to Leyden, from Babylon to Panama, from Amber to Detroit"],
    [8,"11:50","12:40","Conference","Strangling the dragon: modernizing legacy systems with the Strangler Fig pattern"],
    [9,"11:50","12:40","Conference","We created our own AI orchestrator and it became so much more!"],
  ],
];
